esaude-platform-tomcat:
  image: psbrandt-docker-openmrs-refapp-debian.bintray.io/tomcat:2.3.1
  ports:
    - "8080:8080"
    - "5000:5000"
  container_name: esaude-platform-tomcat
  links:
    - esaude-platform-mysql
esaude-platform-mysql:
  image: psbrandt-docker-openmrs-refapp-debian.bintray.io/mysql:2.3.1
  ports:
    - "3306:3306"
  container_name: esaude-platform-mysql
