openmrs-refapp-tomcat:
  image: psbrandt-docker-openmrs-refapp-debian.bintray.io/tomcat:2.3.1
  ports:
    - "8080:8080"
    - "5000:5000"
  container_name: openmrs-refapp-tomcat
  links:
    - openmrs-refapp-mysql
openmrs-refapp-mysql:
  image: psbrandt-docker-openmrs-refapp-debian.bintray.io/mysql:2.3.1
  ports:
    - "3306:3306"
  container_name: openmrs-refapp-mysql
